### ISSUE TITLE
[2016.04.22] Xorg does not start in VirtualBox

### ISSUE THREAD

**Issue by mis2** [Antergos/antergos-iso#57]
I don't know if you are already aware of this issue and I hope this is the right place to report it.

The latest isos (2016.04.22) are affected by this bug: https://bugs.archlinux.org/task/48598

**Comment by Mikaela** [comment]
>￼ *Comment by Stefan Majewsky (majewsky) - Friday, 15 April 2016, 08:07 GMT*
> As a workaround, add `iomem=relaxed` to the kernel command line. I just confirmed it on my VM.

> Source: https://bbs.archlinux.org/viewtopic.php?pid=1619975#p1619975

The issue has also been fixed in upstream/Arch(?):

>  *Comment by Aleks (pethead) - Tuesday, 19 April 2016, 07:21 GMT*
After upgrading VBox to 5.0.18 and reinstalling ./VBoxLinuxAdditions X runs without `iomem=relaxed` in kernel parameters!

I also asked at Telegram:

*@karasu @lots0logs Any plans for releating a new iso because of https://github.com/Antergos/antergos-iso/issues/57 ?*

*It might not seem so important issue, but many people have been hit by that here and most of people try new distributions by putting them on Virtualbox.*

but GitHub is possibly better place to reach the developers especially with the suspect of at least Karasu being kidnapped from Telegram/IRC by octocats in lab coats. :stuck_out_tongue:

**Comment by mis2** [comment]
> The issue has also been fixed in upstream/Arch(?): 

Yes, it's fixed:

> _https://bugs.archlinux.org/task/48598_
> Reason for closing:  Fixed
> Additional comments about closing:  virtualbox 5.0.18-1

-
> most of people try new distributions by putting them on Virtualbox

Good point for considering a new iso release.

**Comment by mis2** [comment]
Fixed with 2016.05.24, so I will close this.
