### ISSUE TITLE
unknown filesystem type 'LVM2_member' - antergos-2016.05.28-x86_64.iso

### ISSUE THREAD

**Issue by satriani-vai** [Antergos/antergos-iso#59]
```
mount: unknown filesystem type 'LVM2_member'
You are now being dropped into an emergency shell.
sh: can't access tty; job control turned off
```
Installed on UEFI with: LUKS + LVM, systemd-boot bootloader and latest Cnchi from https://github.com/Antergos/Cnchi/commit/4b9f9215fc3932dc370a36a6704fa0b4da023799

Can anyone confirm this?

**Comment by karasu** [comment]
I'll test this asap

Please, it would be very helpful if anybody else can confirm this.

**Comment by satriani-vai** [comment]
Here screenshots of my UEFI settings and issue:

![20160530_194330](https://cloud.githubusercontent.com/assets/5981417/15655879/bacaf6d8-26a1-11e6-8d7c-f677cebbcceb.jpg)
![20160530_200317](https://cloud.githubusercontent.com/assets/5981417/15655880/bacbe5fc-26a1-11e6-944d-74f8819e5655.jpg)

**Comment by schulmar** [comment]
I can confirm the exact same issue.

I let the install repartition my SSD and chose to use systemd-boot with LVM and encryption plus a separate home partition.

After some hours in the rescue shell I determined that the `root=UUID=...` in `/proc/cmdline` pointed to `/dev/mapper/cryptAntergos` instead of `/dev/mapper/AntergosVG-AntergosRoot`. After manually entering `/dev/mapper/AntergosVG-AntergosRoot` instead of `UUID=...` I was able to boot into the GUI.

I changed this permanently in `/boot/loader/entries/antergos.conf` and it boots fine now.

**Comment by satriani-vai** [comment]
Take a look [here](https://github.com/Antergos/Cnchi/blob/840aca61ea9bd440c83cd777b4c9d0d22697e1bf/cnchi/installation/boot/systemd_boot.py#L83) ;)

**Comment by satriani-vai** [comment]
@karasu Did you test it?

**Comment by satriani-vai** [comment]
Done. https://github.com/Antergos/Cnchi/commit/dd989c13448a9c73b8544f38223030fc4b8f1839 & https://github.com/Antergos/Cnchi/commit/e3d6c8e9c165baa253447bcbfe3d4a6fff0e837d
